# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    assignees:
      - "marpme"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(dev-deps): "
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*next*"
      dev-dependencies:
        patterns:
          - "react*"
          - "*vitest*"
          - "@typescript-eslint/*"
          - "@commitlint/*"

