name: tests and coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    strategy:
      matrix:
        nodeVersion: [ 16, 18, 19 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeVersion }}
          cache: "npm"
      - name: Install dependencies
        run: npm install --prefer-offline
      - name: Run tests and generate coverage report
        run: npm run coverage
      - if: ${{ matrix.nodeVersion == '18' }}
        name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}